[scanner]
ip_range = "192.168.0.1/24"
port_range = "80,443"
threads = 100
masscan_rate = 1000
save_file = "path to your save file"

[telegram]
chat_id = "your chat id"
bot_token = "your bot token"

[vk]
user_id = "your user id"
access_token = "your community access token"
